analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    invalid_use_of_visible_for_testing_member: error


linter:
  rules:
    always_declare_return_types: true
    unawaited_futures: true
    avoid_void_async: true
    await_only_futures: true
    exhaustive_cases: true

